In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
from sklearn.cluster import KMeans
from scipy.stats import ttest_ind

In [3]:
df = pd.read_csv('/Users/sravankumarshaga/Desktop/Team wine/SPRINT-3/Q4/Wine_type.csv')

In [4]:
df

              Winery              Type           Wine_Name  Quantity
0   Pearmund Cellars       WINE FLIGHT     2019 Chardonnay        86
1   Pearmund Cellars       WINE FLIGHT       2020 Viognier        83
2   Pearmund Cellars       WINE FLIGHT           2021 Rose        80
3   Pearmund Cellars       WINE FLIGHT  2021 Petit Manseng        77
4   Pearmund Cellars       WINE FLIGHT      2019 Ameritage        72
..               ...               ...                 ...       ...
59   Effingham Manor  Glass of Reserve   2020 Kings Ransom        66
60   Effingham Manor  Glass of Reserve        2020 Reserve        31
61   Effingham Manor  Glass of Reserve   2020 Petit Verdot        29
62   Effingham Manor  Glass of Reserve         2020 Tannat        26
63   Effingham Manor           TASTING        Wine Tasting       142

[64 rows x 4 columns]

In [5]:
Pearmund_Cellars = df[df['Winery'] == 'Pearmund Cellars']
Pearmund_Cellars

              Winery                 Type                Wine_Name  Quantity
0   Pearmund Cellars          WINE FLIGHT          2019 Chardonnay        86
1   Pearmund Cellars          WINE FLIGHT            2020 Viognier        83
2   Pearmund Cellars          WINE FLIGHT                2021 Rose        80
3   Pearmund Cellars          WINE FLIGHT       2021 Petit Manseng        77
4   Pearmund Cellars          WINE FLIGHT           2019 Ameritage        72
5   Pearmund Cellars          WINE FLIGHT            2019 Riesling        64
6   Pearmund Cellars          WINE FLIGHT            2022 Sunshine        54
7   Pearmund Cellars          WINE FLIGHT           2019 Cab Franc        50
8   Pearmund Cellars          WINE FLIGHT        2020 Petit Verdot        38
9   Pearmund Cellars  WINE FLIGHT Reserve   Â 7th Mission Black Ops       115
10  Pearmund Cellars  WINE FLIGHT Reserve    2019 Anniversary Wine       109
11  Pearmund Cellars  WINE FLIGHT Reserve   2019 Cab Franc Reserve        52
12  Pearmund Cellars  WINE FLIGHT Reserve   2020 Ameritage Reserve        60
13  Pearmund Cellars  WINE FLIGHT Reserve          2020 PV Reserve        55
14  Pearmund Cellars  WINE FLIGHT Reserve                 Cab Sauv        99
15  Pearmund Cellars        Glass of Wine          2019 Chardonnay        39
16  Pearmund Cellars        Glass of Wine            Petit Manseng        26
17  Pearmund Cellars        Glass of Wine            2020 Viognier        24
18  Pearmund Cellars        Glass of Wine            2022 Sunshine        20
19  Pearmund Cellars        Glass of Wine           2019 Ameritage        17
20  Pearmund Cellars        Glass of Wine            2019 Riesling        16
21  Pearmund Cellars        Glass of Wine           2019 Cab Franc        14
22  Pearmund Cellars        Glass of Wine                2021 Rose        14
23  Pearmund Cellars        Glass of Wine        2020 Petit Verdot         7
24  Pearmund Cellars     Glass of Reserve    Â 7th Missio Black Ops        27
25  Pearmund Cellars     Glass of Reserve    2019 Anniversary Wine        23
26  Pearmund Cellars     Glass of Reserve   2019 Cab Franc Reserve        17
27  Pearmund Cellars     Glass of Reserve   2020 Ameritage Reserve         8
28  Pearmund Cellars     Glass of Reserve          2020 PV Reserve        11
29  Pearmund Cellars     Glass of Reserve                 Cab Sauv        16
30  Pearmund Cellars         Reserve Trio    7th Missio Black Ops         34
31  Pearmund Cellars         Reserve Trio    2019 Anniversary Wine        24
32  Pearmund Cellars         Reserve Trio   2020 Ameritage Reserve        20
33  Pearmund Cellars         Reserve Trio   2019 Cab Sauv Reserve         20
34  Pearmund Cellars         Reserve Trio  2019 Cab Franc Reserve         17
35  Pearmund Cellars         Reserve Trio          2020 PV Reserve        16
36  Pearmund Cellars              TASTING              TASTING $18       136

In [30]:

df_grouped_1 = Pearmund_Cellars.groupby('Type')['Quantity'].sum().reset_index()
df_grouped_1

                  Type  Quantity
0     Glass of Reserve       102
1        Glass of Wine       177
2         Reserve Trio       131
3              TASTING       136
4          WINE FLIGHT       604
5  WINE FLIGHT Reserve       490

In [31]:
wine_flight = df_grouped_1.loc[df_grouped_1['Type'].isin(['WINE FLIGHT', 'WINE FLIGHT Reserve']), 'Quantity'].sum()
new_row = pd.DataFrame({'Type': ['Wine Flight'], 'Quantity': [wine_flight]})
df_grouped_1 = pd.concat([df_grouped_1, new_row], ignore_index=True)
df_grouped_1

                  Type  Quantity
0     Glass of Reserve       102
1        Glass of Wine       177
2         Reserve Trio       131
3              TASTING       136
4          WINE FLIGHT       604
5  WINE FLIGHT Reserve       490
6          Wine Flight      1094

In [32]:
index_of_wine_flight = df_grouped_1[df_grouped_1['Type'] == 'Wine Flight'].index[0]
df_grouped_1.loc[index_of_wine_flight, 'Quantity'] //= 3

In [33]:
df_grouped_1

                  Type  Quantity
0     Glass of Reserve       102
1        Glass of Wine       177
2         Reserve Trio       131
3              TASTING       136
4          WINE FLIGHT       604
5  WINE FLIGHT Reserve       490
6          Wine Flight       364

In [36]:
file_path = 'PC_flight.csv'

# Save to CSV
df_grouped_1.to_csv(file_path, index=False)

In [21]:
Effingham_Manor = df[df['Winery'] == 'Effingham Manor']
Effingham_Manor

             Winery                 Type           Wine_Name  Quantity
37  Effingham Manor        Glass of Wine     2019 Chardonnay        40
38  Effingham Manor        Glass of Wine    2022 Celebration        51
39  Effingham Manor        Glass of Wine         Mulled wine       114
40  Effingham Manor        Glass of Wine  2022 Petit Manseng        43
41  Effingham Manor        Glass of Wine       2019 Meritage        34
42  Effingham Manor        Glass of Wine           2021 Rose        29
43  Effingham Manor        Glass of Wine         2019 Merlot        19
44  Effingham Manor        Glass of Wine       2020 Viognier        15
45  Effingham Manor        Glass of Wine          2019 Snort         6
46  Effingham Manor  WINE FLIGHT Reserve        2020 Reserve        69
47  Effingham Manor  WINE FLIGHT Reserve   2020 Kings Ransom        60
48  Effingham Manor          WINE FLIGHT  2022 Petit Manseng        53
49  Effingham Manor          WINE FLIGHT    2022 Celebration        49
50  Effingham Manor          WINE FLIGHT           2021 Rose        47
51  Effingham Manor  WINE FLIGHT Reserve   2020 Petit Verdot        43
52  Effingham Manor          WINE FLIGHT       2019 Meritage        42
53  Effingham Manor  WINE FLIGHT Reserve         2020 Tannat        39
54  Effingham Manor          WINE FLIGHT     2019 Chardonnay        36
55  Effingham Manor          WINE FLIGHT       2020 Viognier        32
56  Effingham Manor          WINE FLIGHT          2019 Snort        14
57  Effingham Manor          WINE FLIGHT         Mulled wine         4
58  Effingham Manor          WINE FLIGHT        2019  Merlot        29
59  Effingham Manor     Glass of Reserve   2020 Kings Ransom        66
60  Effingham Manor     Glass of Reserve        2020 Reserve        31
61  Effingham Manor     Glass of Reserve   2020 Petit Verdot        29
62  Effingham Manor     Glass of Reserve         2020 Tannat        26
63  Effingham Manor              TASTING        Wine Tasting       142

In [22]:

df_grouped_2 = Effingham_Manor.groupby('Type')['Quantity'].sum().reset_index()
df_grouped_2

                  Type  Quantity
0     Glass of Reserve       152
1        Glass of Wine       351
2              TASTING       142
3          WINE FLIGHT       306
4  WINE FLIGHT Reserve       211

In [23]:
wine_flight = df_grouped_2.loc[df_grouped_2['Type'].isin(['WINE FLIGHT', 'WINE FLIGHT Reserve']), 'Quantity'].sum()
new_row = pd.DataFrame({'Type': ['Wine Flight'], 'Quantity': [wine_flight]})
df_grouped_2 = pd.concat([df_grouped_2, new_row], ignore_index=True)
df_grouped_2

                  Type  Quantity
0     Glass of Reserve       152
1        Glass of Wine       351
2              TASTING       142
3          WINE FLIGHT       306
4  WINE FLIGHT Reserve       211
5          Wine Flight       517

In [34]:
index_of_wine_flight = df_grouped_2[df_grouped_2['Type'] == 'Wine Flight'].index[0]
df_grouped_2.loc[index_of_wine_flight, 'Quantity'] //= 3
df_grouped_2

                  Type  Quantity
0     Glass of Reserve       152
1        Glass of Wine       351
2              TASTING       142
3          WINE FLIGHT       306
4  WINE FLIGHT Reserve       211
5          Wine Flight       172

In [35]:
file_path = 'Ef_flight.csv'

# Save to CSV
df_grouped_2.to_csv(file_path, index=False)

In [7]:
Pearmund_Cellars_1 = Pearmund_Cellars[Pearmund_Cellars['Type'] == 'Glass of Wine']
Pearmund_Cellars_1 = Pearmund_Cellars_1.sort_values(by='Quantity', ascending=False)



Effingham_Manor_1 = Effingham_Manor[Effingham_Manor['Type'] == 'Glass of Wine']
Effingham_Manor_1 = Effingham_Manor_1.sort_values(by='Quantity', ascending=False)




Pearmund_Cellars_1 = Pearmund_Cellars_1.reset_index(drop=True)
Effingham_Manor_1 = Effingham_Manor_1.reset_index(drop=True)

print('\t\t\033[1m2023-9-24 to 2023-10-22\n\033[0m')
print(Pearmund_Cellars_1, "\n \n", Effingham_Manor_1)

		2023-9-24 to 2023-10-22

             Winery           Type          Wine_Name  Quantity
0  Pearmund Cellars  Glass of Wine    2019 Chardonnay        39
1  Pearmund Cellars  Glass of Wine      Petit Manseng        26
2  Pearmund Cellars  Glass of Wine      2020 Viognier        24
3  Pearmund Cellars  Glass of Wine      2022 Sunshine        20
4  Pearmund Cellars  Glass of Wine     2019 Ameritage        17
5  Pearmund Cellars  Glass of Wine      2019 Riesling        16
6  Pearmund Cellars  Glass of Wine     2019 Cab Franc        14
7  Pearmund Cellars  Glass of Wine          2021 Rose        14
8  Pearmund Cellars  Glass of Wine  2020 Petit Verdot         7

             Winery           Type           Wine_Name  Quantity
0  Effingham Manor  Glass of Wine         Mulled wine       114
1  Effingham Manor  Glass of Wine    2022 Celebration        51
2  Effingham Manor  Glass of Wine  2022 Petit Manseng        43
3  Effingham Manor  Glass of Wine     2019 Chardonnay        40
4  Effingham Manor  Glass of Wine       2019 Meritage        34
5  Effingham Manor  Glass of Wine           2021 Rose        29
6  Effingham Manor  Glass of Wine         2019 Merlot        19
7  Effingham Manor  Glass of Wine       2020 Viognier        15
8  Effingham Manor  Glass of Wine          2019 Snort         6

In [18]:
file_path = 'Effingham_Manor_1.csv'

# Save to CSV
Effingham_Manor_1.to_csv(file_path, index=False)

In [ ]:
file_path = 'Pearmund_Cellars_1.csv'

# Save to CSV
Pearmund_Cellars_1.to_csv(file_path, index=False)

In [8]:
Pearmund_Cellars_2 = Pearmund_Cellars[Pearmund_Cellars['Type'] == 'Glass of Reserve']
Pearmund_Cellars_2 = Pearmund_Cellars_2.sort_values(by='Quantity', ascending=False)

Effingham_Manor_2 = Effingham_Manor[Effingham_Manor['Type'] == 'Glass of Reserve']
Effingham_Manor_2 = Effingham_Manor_2.sort_values(by='Quantity', ascending=False)


Pearmund_Cellars_2 = Pearmund_Cellars_2.reset_index(drop=True)
Effingham_Manor_2= Effingham_Manor_2.reset_index(drop=True)

print('\t\t\033[1m2023-9-24 to 2023-10-22\n\033[0m')


print(Pearmund_Cellars_2, "\n \n", Effingham_Manor_2)

		2023-9-24 to 2023-10-22

             Winery              Type               Wine_Name  Quantity
0  Pearmund Cellars  Glass of Reserve   Â 7th Missio Black Ops        27
1  Pearmund Cellars  Glass of Reserve   2019 Anniversary Wine        23
2  Pearmund Cellars  Glass of Reserve  2019 Cab Franc Reserve        17
3  Pearmund Cellars  Glass of Reserve                Cab Sauv        16
4  Pearmund Cellars  Glass of Reserve         2020 PV Reserve        11
5  Pearmund Cellars  Glass of Reserve  2020 Ameritage Reserve         8

             Winery              Type          Wine_Name  Quantity
0  Effingham Manor  Glass of Reserve  2020 Kings Ransom        66
1  Effingham Manor  Glass of Reserve       2020 Reserve        31
2  Effingham Manor  Glass of Reserve  2020 Petit Verdot        29
3  Effingham Manor  Glass of Reserve        2020 Tannat        26

In [20]:
file_path = 'Pearmund_Cellars_2.csv'

# Save to CSV
Pearmund_Cellars_2.to_csv(file_path, index=False)

In [21]:
file_path = 'Effingham_Manor_2.csv'

# Save to CSV
Effingham_Manor_2.to_csv(file_path, index=False)

In [9]:

Pearmund_Cellars_3 = Pearmund_Cellars[Pearmund_Cellars['Type'] == 'WINE FLIGHT']
Pearmund_Cellars_3 = Pearmund_Cellars_3.sort_values(by='Quantity', ascending=False)

Effingham_Manor_3= Effingham_Manor[Effingham_Manor['Type'] == 'WINE FLIGHT']
Effingham_Manor_3 = Effingham_Manor_3.sort_values(by='Quantity', ascending=False)


Pearmund_Cellars_3 = Pearmund_Cellars_3.reset_index(drop=True)
Effingham_Manor_3= Effingham_Manor_3.reset_index(drop=True)

print('\t\t\033[1m2023-9-24 to 2023-10-22\n\033[0m')

print(Pearmund_Cellars_3, "\n \n", Effingham_Manor_3)

		2023-9-24 to 2023-10-22

             Winery         Type           Wine_Name  Quantity
0  Pearmund Cellars  WINE FLIGHT     2019 Chardonnay        86
1  Pearmund Cellars  WINE FLIGHT       2020 Viognier        83
2  Pearmund Cellars  WINE FLIGHT           2021 Rose        80
3  Pearmund Cellars  WINE FLIGHT  2021 Petit Manseng        77
4  Pearmund Cellars  WINE FLIGHT      2019 Ameritage        72
5  Pearmund Cellars  WINE FLIGHT       2019 Riesling        64
6  Pearmund Cellars  WINE FLIGHT       2022 Sunshine        54
7  Pearmund Cellars  WINE FLIGHT      2019 Cab Franc        50
8  Pearmund Cellars  WINE FLIGHT   2020 Petit Verdot        38

             Winery         Type           Wine_Name  Quantity
0  Effingham Manor  WINE FLIGHT  2022 Petit Manseng        53
1  Effingham Manor  WINE FLIGHT    2022 Celebration        49
2  Effingham Manor  WINE FLIGHT           2021 Rose        47
3  Effingham Manor  WINE FLIGHT       2019 Meritage        42
4  Effingham Manor  WINE FLIGHT     2019 Chardonnay        36
5  Effingham Manor  WINE FLIGHT       2020 Viognier        32
6  Effingham Manor  WINE FLIGHT        2019  Merlot        29
7  Effingham Manor  WINE FLIGHT          2019 Snort        14
8  Effingham Manor  WINE FLIGHT         Mulled wine         4

In [10]:

df_grouped = Pearmund_Cellars_3.groupby('Type')['Quantity'].sum().reset_index()
df_grouped

          Type  Quantity
0  WINE FLIGHT       604

In [23]:
file_path = 'Pearmund_Cellars_3.csv'

# Save to CSV
Pearmund_Cellars_3.to_csv(file_path, index=False)

In [24]:
file_path = 'Effingham_Manor_3.csv'

# Save to CSV
Effingham_Manor_3.to_csv(file_path, index=False)

In [25]:


Pearmund_Cellars_4 = Pearmund_Cellars[Pearmund_Cellars['Type'] == 'WINE FLIGHT Reserve']
Pearmund_Cellars_4 = Pearmund_Cellars_4.sort_values(by='Quantity', ascending=False)

Effingham_Manor_4= Effingham_Manor[Effingham_Manor['Type'] == 'WINE FLIGHT Reserve']
Effingham_Manor_4 = Effingham_Manor_4.sort_values(by='Quantity', ascending=False)


Pearmund_Cellars_4 = Pearmund_Cellars_4.reset_index(drop=True)
Effingham_Manor_4= Effingham_Manor_4.reset_index(drop=True)

print('\t\t\033[1m2023-9-24 to 2023-10-22\n\033[0m')

print(Pearmund_Cellars_4, "\n \n", Effingham_Manor_4)

		2023-9-24 to 2023-10-22

             Winery                 Type               Wine_Name  Quantity
0  Pearmund Cellars  WINE FLIGHT Reserve  Â 7th Mission Black Ops       115
1  Pearmund Cellars  WINE FLIGHT Reserve   2019 Anniversary Wine       109
2  Pearmund Cellars  WINE FLIGHT Reserve                Cab Sauv        99
3  Pearmund Cellars  WINE FLIGHT Reserve  2020 Ameritage Reserve        60
4  Pearmund Cellars  WINE FLIGHT Reserve         2020 PV Reserve        55
5  Pearmund Cellars  WINE FLIGHT Reserve  2019 Cab Franc Reserve        52

             Winery                 Type          Wine_Name  Quantity
0  Effingham Manor  WINE FLIGHT Reserve       2020 Reserve        69
1  Effingham Manor  WINE FLIGHT Reserve  2020 Kings Ransom        60
2  Effingham Manor  WINE FLIGHT Reserve  2020 Petit Verdot        43
3  Effingham Manor  WINE FLIGHT Reserve        2020 Tannat        39

In [26]:
file_path = 'Pearmund_Cellars_4.csv'

# Save to CSV
Pearmund_Cellars_4.to_csv(file_path, index=False)

In [27]:
file_path = 'Effingham_Manor_4.csv'

# Save to CSV
Effingham_Manor_4.to_csv(file_path, index=False)

In [28]:


Pearmund_Cellars_5 = Pearmund_Cellars[Pearmund_Cellars['Type'] == 'TASTING']
Pearmund_Cellars_5 = Pearmund_Cellars_5.sort_values(by='Quantity', ascending=False)
Pearmund_Cellars_5 = Pearmund_Cellars_5.reset_index(drop=True)

Effingham_Manor_5 = Effingham_Manor[Effingham_Manor['Type'] == 'TASTING']
Effingham_Manor_5 = Effingham_Manor_5.sort_values(by='Quantity', ascending=False)
Effingham_Manor_5 = Effingham_Manor_5.reset_index(drop=True)


Pearmund_Cellars_6 = Pearmund_Cellars[Pearmund_Cellars['Type'] == 'Reserve Trio']
Pearmund_Cellars_6 = Pearmund_Cellars_6.sort_values(by='Quantity', ascending=False)
Pearmund_Cellars_6 = Pearmund_Cellars_6.reset_index(drop=True)



print('\t\t\033[1m2023-9-24 to 2023-10-22\n\033[0m')

print(Pearmund_Cellars_5, "\n \n", Effingham_Manor_5, "\n\n\n\n", Pearmund_Cellars_6)

		2023-9-24 to 2023-10-22

             Winery     Type    Wine_Name  Quantity
0  Pearmund Cellars  TASTING  TASTING $18       136

             Winery     Type     Wine_Name  Quantity
0  Effingham Manor  TASTING  Wine Tasting       142



              Winery          Type                Wine_Name  Quantity
0  Pearmund Cellars  Reserve Trio    7th Missio Black Ops         34
1  Pearmund Cellars  Reserve Trio    2019 Anniversary Wine        24
2  Pearmund Cellars  Reserve Trio   2020 Ameritage Reserve        20
3  Pearmund Cellars  Reserve Trio   2019 Cab Sauv Reserve         20
4  Pearmund Cellars  Reserve Trio  2019 Cab Franc Reserve         17
5  Pearmund Cellars  Reserve Trio          2020 PV Reserve        16

In [29]:
file_path = 'Pearmund_Cellars_5.csv'

# Save to CSV
Pearmund_Cellars_5.to_csv(file_path, index=False)

In [30]:
file_path = 'Effingham_Manor_5.csv'

# Save to CSV
Effingham_Manor_5.to_csv(file_path, index=False)

In [31]:
file_path = 'Pearmund_Cellars_6.csv'

# Save to CSV
Pearmund_Cellars_6.to_csv(file_path, index=False)